package EulerProjectFinished;


import java.util.ArrayList;
import java.util.List;

//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.
public class P2EvenFibonacciSum {
	
	public static void main(String []args){

		double fTerm = 1;
		double sTerm = 2;
		int index = 0;
		int evenSum = 0;
		
		List<Double> allFibonacci = new ArrayList<>();
		allFibonacci.add(0,fTerm);
		allFibonacci.add(1,sTerm);
		
		List<Integer> evenFibonacci = new ArrayList<>();
		
		for (int i = 2; i<40; i++){
			allFibonacci.add(i,allFibonacci.get(index)+allFibonacci.get(index+1));
			index++;
			
		}
		for (index = 0; index <allFibonacci.size();index++){
			
			if(allFibonacci.get(index)% 2 == 0 && allFibonacci.get(index)<4000000)evenSum+=allFibonacci.get(index);
		}
		System.out.println(evenSum);
	}
	
}
